server:
  port: 8970

spring:
  application:
    name: upcomingAds
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    async:
      request-timeout: 80000
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB

ai:
  elevenLabs:
    url: https://api.elevenlabs.io
    name: elevenLabsClient
  claude:
    url: https://api.anthropic.com/v1
    name: claudeClient

api:
  elevenlabs:
    key: ${ELEVENLABS_API_KEY}
  claude:
    key: ${ANTHROPIC_API_KEY}




