server:
  port: 8970

spring:
  application:
    name: upcomingAds
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    async:
      request-timeout: 80000
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB

chatGpt:
  model: ${MODEL_CHATGPT:gpt-4-turbo}
  role:  ${ROLE_CHATGPT:user}

ai:
  elevenLabs:
    url: https://api.elevenlabs.io
    name: elevenLabsClient
  claude:
    url: https://api.anthropic.com/v1
    name: claudeClient
  chatGpt:
    url: https://api.openai.com/v1
    name: openAiClient


api:
  elevenlabs:
    key: ${ELEVENLABS_API_KEY}
  claude:
    key: ${ANTHROPIC_API_KEY}
  chatGpt:
    key: ${OPENAI_API_KEY}




