server:
  port: 1234

spring:
  application:
    name: upcomingAds
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    async:
      request-timeout: 80000

api:
  elevenlabs:
    key: ${ELEVENLABS_API_KEY}




